apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-minuto
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          restartPolicy: Never
          containers:
            - name: echo-container
              image: busybox:latest
              command: ["echo", "Hello world cada minuto"]